image: python:3.11

stages:
  - build_and_run

build_and_run:
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  stage: build_and_run
  script:
    - |
      apt-get update && apt-get install -y --no-install-recommends freeglut3-dev libxkbcommon-x11-0 libdbus-1-3
      pip install poetry
      poetry install --no-interaction --no-root -E build -E format # https://github.com/python-poetry/poetry/issues/1227
      source $(poetry env info --path)/bin/activate
      yapf -drp --no-local-style --style "facebook" src/
